module.exports = [
    {
        "naam": "Heide en Vennen",
        "plaats": "Drouwen",
        "foto": "http://3.bp.blogspot.com/-mfhJdBRccEY/UEph2j5JWiI/AAAAAAAAE3k/9bPKprZAbQM/s1600/boomkroonpad+15.jpg",
        "gebied": "Hondsrug",
        "provincie": "Drenthe",
        "website": "https://www.staatsbosbeheer.nl/routes/hondsrug/wandelroute-heide-en-vennen",
        "afstand": "4",
        "beschrijving": "Stel je voor hoe het landschap op de Hondsrug er zo'n 60 jaar geleden uitzag. Eindeloze heidevelden, hier en daar wat bomen en heel veel vennetjes.",
        "bewegwijzering": "paars",
        "organisatie": "Staatsbosbeheer",
        "auteur": "5fcf955ebbb92d0751bfa473",
    },
    {
        "naam": "Bomen",
        "plaats": "Drouwen",
        "foto": "https://www.staatsbosbeheer.nl/-/media/hondsrug/hondsrug-1.jpg",
        "gebied": "Hondsrug",
        "provincie": "Drenthe",
        "website": "https://www.staatsbosbeheer.nl/routes/hondsrug/wandelroute-bomen",
        "afstand": "3",
        "beschrijving": "Al wandelend door de boswachterij Gieten-Borger op de Hondsrug kun je heel wat indrukwekkende bomen bekijken en herkennen. Tip: routebeschrijving bij startpunt.",
        "bewegwijzering": "geel",
        "organisatie": "Staatsbosbeheer",
        "auteur": "5fcf955ebbb92d0751bfa473",
    },
    {
        "naam": "Rondje Tweelingen",
        "plaats": "Schoonloo",
        "foto": "https://www.staatsbosbeheer.nl/-/media/14-florafauna/vogels/grote-bonte-specht-bij-boomholte.jpg",
        "gebied": "Hart van Drenthe",
        "provincie": "Drenthe",
        "websitewebsite": "https://www.staatsbosbeheer.nl/routes/hart-van-drenthe/wandelroute-rondje-tweelingen",
        "afstand": "4.7",
        "beschrijving": "Rondzwerven over zonverwarmde zandpaden in een uitgestrekt bos in het Hart van Drenthe. Het geroffel van spechten of de roep van een verre buizerd doorbreekt af en toe de stilte.",
        "bewegwijzering": "geel",
        "organisatie": "Staatsbosbeheer",
        "auteur": "5fcf955ebbb92d0751bfa473",
    },
    {
        "naam": "Melkwegpad",
        "plaats": "Hooghalen",
        "foto": "https://hondsdol.nl/wp-content/uploads/2018/02/Hart-van-Drenthe-5.jpg",
        "gebied": "Hart van Drenthe",
        "provincie": "Drenthe",
        "website": "https://www.staatsbosbeheer.nl/routes/hart-van-drenthe/wandelroute-melkwegpad",
        "afstand": "2.2",
        "beschrijving": "Dit familiepad gaat langs het voormalige kamp Westerbork, het Hingsteveen en de radiosterrenwacht. Deze wandeling door het Hart van Drenthe is toegankelijk met rolstoel en rollator.",
        "bewegwijzering": "zwart",
        "organisatie": "Staatsbosbeheer",
        "auteur": "5fcf955ebbb92d0751bfa473",
    },
]